;;; zshrs-mode.el --- Major mode for the zshrs shell -*- lexical-binding: t; -*-

;; Copyright (c) 2026 MenkeTechnologies

;; Author: MenkeTechnologies
;; URL: https://github.com/MenkeTechnologies/emacs-zsh
;; Version: 0.1.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: languages, zsh, zshrs, shell

;; This file is not part of GNU Emacs.

;;; Commentary:

;; A major mode for zshrs — the first-ever Rust rewrite of the zsh shell.
;; Provides:
;;
;;   - filetype detection for zsh dotfiles, `*.zsh' / theme files, and
;;     `zsh' / `zshrs' shebangs
;;   - syntax highlighting driven by the binary's own reflection tables: the
;;     builtin surface, zshrs-specific extension builtins (their own face),
;;     special variables, control + declaration keywords, sigil variables,
;;     strings, and comments
;;   - shell-block + brace-aware indentation
;;   - language-server integration via `zshrs --lsp' (eglot + lsp-mode)
;;   - lint via `zshrs -n' on the buffer (errors to stderr, rc=1)
;;
;; This mode deliberately does NOT clobber the built-in `sh-mode'; it is a
;; separate `zshrs-mode' you opt into.  The builtin / extension / special-var
;; tables live in `zshrs-stdlib.el' as `regexp-opt' alternations (the surface
;; is small — ~137 builtins + ~113 extensions + ~245 special vars — so a single
;; regexp per category fits comfortably under Emacs' regexp-size limit),
;; generated by scripts/gen-stdlib.sh.  Regenerate after a zshrs upgrade.

;;; Code:

(require 'zshrs-stdlib)

;; Optional integrations — referenced only inside `with-eval-after-load' blocks,
;; declared here so the byte-compiler stays quiet when they are absent.
(defvar eglot-server-programs)
(defvar lsp-language-id-configuration)
(declare-function make-lsp-client "lsp-mode")
(declare-function lsp-register-client "lsp-mode")
(declare-function lsp-stdio-connection "lsp-mode")
(declare-function lsp-activate-on "lsp-mode")

(defgroup zshrs nil
  "Major mode for the zshrs shell."
  :group 'languages
  :prefix "zshrs-")

(defcustom zshrs-executable "zshrs"
  "Path to the zshrs executable, used for the language server and linter."
  :type 'string
  :group 'zshrs)

(defcustom zshrs-indent-offset 4
  "Number of spaces per indentation level in `zshrs-mode'."
  :type 'integer
  :group 'zshrs)

(defface zshrs-extension-face
  '((t :inherit font-lock-builtin-face :weight bold))
  "Face for zshrs-specific extension builtins (the world-first additions).
Bold so the zshrs extensions stand out from the inherited zsh builtins."
  :group 'zshrs)

;;; Keyword categories.  These lists are small, so a plain `regexp-opt' is fine.
;;; The names here are kept in sync with the keyword-exclusion list in
;;; scripts/gen-stdlib.sh so a name never lands in two categories.

(defconst zshrs--control-keywords
  '("always" "case" "do" "done" "elif" "else" "end" "esac" "fi" "for"
    "foreach" "if" "in" "repeat" "select" "then" "until" "while" "function"
    "break" "continue" "exit" "logout" "return")
  "zshrs control-flow / block keywords.")

(defconst zshrs--declaration-keywords
  '("declare" "export" "float" "integer" "let" "local" "readonly" "set"
    "shift" "typeset")
  "zshrs declaration keywords.")

(defconst zshrs-font-lock-keywords
  `(;; Keyword categories (small, safe regexp-opt).
    (,(regexp-opt zshrs--control-keywords 'symbols) . font-lock-keyword-face)
    (,(regexp-opt zshrs--declaration-keywords 'symbols) . font-lock-keyword-face)
    ;; zshrs-specific extensions get their own bold face — listed BEFORE the
    ;; general builtins so they win their own face (the two sets are disjoint).
    (,zshrs-extensions-regexp . 'zshrs-extension-face)
    ;; The inherited builtin surface.
    (,zshrs-builtins-regexp . font-lock-builtin-face)
    ;; Special variables — both `$NAME' and a bare `NAME' occurrence (e.g. in a
    ;; parameter expansion or assignment).
    (,(concat "\\$\\(" zshrs-special-vars-regexp "\\)")
     (1 font-lock-variable-name-face))
    (,zshrs-special-vars-regexp . font-lock-variable-name-face)
    ;; Punctuation sigil variables: $? $@ $# $$ $! $* $- $0..$9.
    ("\\$[?@#$!*0-9-]" . font-lock-constant-face)
    ;; ${ ... } parameter expansion + general $name / ${name} variables.
    ("\\${[^}]*}" . font-lock-variable-name-face)
    ("\\$[A-Za-z_][A-Za-z0-9_]*" . font-lock-variable-name-face))
  "Font-lock keywords for `zshrs-mode'.")

;;; Syntax table.

(defvar zshrs-mode-syntax-table
  (let ((st (make-syntax-table)))
    (modify-syntax-entry ?# "<" st)     ; line comment start
    (modify-syntax-entry ?\n ">" st)    ; comment end
    (modify-syntax-entry ?_ "_" st)     ; symbol constituent
    (modify-syntax-entry ?\" "\"" st)   ; double-quoted string
    (modify-syntax-entry ?\' "\"" st)   ; single-quoted string
    (modify-syntax-entry ?\` "\"" st)   ; backtick command substitution
    (modify-syntax-entry ?\\ "\\" st)   ; escape
    (modify-syntax-entry ?$ "." st)     ; sigils as punctuation
    (modify-syntax-entry ?@ "." st)
    st)
  "Syntax table for `zshrs-mode'.")

;;; Indentation — shell-block + brace aware (do/done, then/fi, case/esac,
;;; if/fi) plus paren/brace/bracket nesting.

(defconst zshrs--block-open-re
  "\\(?:^\\|[ \t;]\\)\\(?:do\\|then\\|in\\|else\\|elif\\|case\\|always\\)\\_>"
  "Regexp for shell keywords that open a deeper indent level on the next line.")

(defconst zshrs--block-close-re
  "^[ \t]*\\(?:done\\|fi\\|esac\\|else\\|elif\\|then\\|[)}]\\)"
  "Regexp for shell keywords / closers that dedent the current line.")

(defun zshrs-indent-line ()
  "Indent the current line for `zshrs-mode'."
  (interactive)
  (let ((indent 0)
        (offset zshrs-indent-offset))
    (save-excursion
      (beginning-of-line)
      (let ((closes (looking-at-p zshrs--block-close-re)))
        (when (zerop (forward-line -1))
          (while (and (looking-at-p "[ \t]*$") (zerop (forward-line -1))))
          (setq indent (current-indentation))
          ;; Previous line opens a brace/paren/bracket (ignoring a trailing
          ;; comment), or ends in a shell block-opener keyword: bump a level.
          (when (or (looking-at-p ".*[[({][ \t]*\\(#.*\\)?$")
                    (looking-at-p (concat ".*" zshrs--block-open-re
                                          "[ \t]*\\(#.*\\)?$")))
            (setq indent (+ indent offset))))
        (when closes
          (setq indent (max 0 (- indent offset))))))
    (if (<= (current-column) (current-indentation))
        (indent-line-to indent)
      (save-excursion (indent-line-to indent)))))

;;; Lint — run `zshrs -n' on the buffer; errors come back on stderr, rc=1.

(defun zshrs-lint-buffer ()
  "Lint the current buffer with `zshrs -n'.
Sends the buffer on stdin; shows the diagnostics in a buffer.  Returns the
process exit status (0 = clean, non-zero = errors)."
  (interactive)
  (let ((out (get-buffer-create "*zshrs-lint*"))
        status)
    (with-current-buffer out (erase-buffer))
    (setq status
          (call-process-region
           (point-min) (point-max) zshrs-executable nil out nil "-n"))
    (if (eq status 0)
        (message "zshrs -n: clean")
      (display-buffer out)
      (message "zshrs -n: errors (rc=%s)" status))
    status))

;;; LSP integration — eglot (built in since Emacs 29) and lsp-mode, both
;;; optional and configured lazily.

(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               `(zshrs-mode . (,zshrs-executable "--lsp"))))

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration '(zshrs-mode . "zshrs"))
  (when (fboundp 'lsp-register-client)
    (lsp-register-client
     (make-lsp-client
      :new-connection (lsp-stdio-connection
                       (lambda () (list zshrs-executable "--lsp")))
      :activation-fn (lsp-activate-on "zshrs")
      :server-id 'zshrs-lsp))))

;;;###autoload
(define-derived-mode zshrs-mode prog-mode "Zshrs"
  "Major mode for editing zshrs shell source.

\\{zshrs-mode-map}"
  :syntax-table zshrs-mode-syntax-table
  (setq-local font-lock-defaults '(zshrs-font-lock-keywords))
  (setq-local comment-start "# ")
  (setq-local comment-start-skip "#+[ \t]*")
  (setq-local comment-end "")
  (setq-local indent-line-function #'zshrs-indent-line)
  (setq-local indent-tabs-mode nil)
  (setq-local tab-width zshrs-indent-offset))

;;;###autoload
(progn
  (dolist (pat '("\\.zsh\\'" "\\.zshenv\\'" "\\.zprofile\\'" "\\.zlogin\\'"
                 "\\.zlogout\\'" "\\.zsh-theme\\'"
                 "\\.zshrc\\'" "\\.zpreztorc\\'"
                 "/\\.?zshrc\\'" "/\\.?zshenv\\'" "/\\.?zprofile\\'"
                 "/\\.?zlogin\\'" "/\\.?zlogout\\'" "/\\.?zpreztorc\\'"))
    (add-to-list 'auto-mode-alist (cons pat 'zshrs-mode))))

;;;###autoload
(progn
  (add-to-list 'interpreter-mode-alist '("zsh" . zshrs-mode))
  (add-to-list 'interpreter-mode-alist '("zshrs" . zshrs-mode)))

(provide 'zshrs-mode)
;;; zshrs-mode.el ends here
