;;; gen-stdlib.el --- Generate zshrs-stdlib.el -*- lexical-binding: t; -*-

;; Run from scripts/gen-stdlib.sh:
;;   emacs --batch -l scripts/gen-stdlib.el \
;;     --eval '(zshrs-gen "builtins.txt" "extensions.txt" "specialvars.txt" \
;;                        "out.el" "VER" "NB" "NX" "NS")'
;;
;; All regexp computation and file writing happens inside Emacs, so no shell
;; escaping ever touches the (backslash-heavy) regexp strings.  zshrs has a
;; SMALL surface (~137 builtins + ~113 extensions + ~245 special vars), so a
;; plain `regexp-opt' over each category is fine — no hash tables, no
;; "Regular expression too big" overflow.

;;; Code:

(require 'cl-lib)

(defun zshrs-gen--words (file)
  "Return the non-empty lines of FILE as a list of strings."
  (split-string
   (with-temp-buffer (insert-file-contents file) (buffer-string))
   "\n" t "[ \t\r]+"))

(defun zshrs-gen--regexp-form (var words docstring)
  "Return an Elisp `defconst' form binding VAR to (regexp-opt WORDS \\='symbols).
The alternation is precomputed at generation time so loading the package is a
single `defconst', not a runtime `regexp-opt' call."
  (format "(defconst %s\n  %S\n  %S)\n\n"
          var (regexp-opt words 'symbols) docstring))

(defun zshrs-gen (builtins-file extensions-file specialvars-file
                  out-file ver nbuiltins nextensions nspecialvars)
  "Write OUT-FILE from the three word-list files.
VER, NBUILTINS, NEXTENSIONS and NSPECIALVARS are metadata strings for the
header."
  (let ((builtins  (zshrs-gen--words builtins-file))
        (extensions (zshrs-gen--words extensions-file))
        (specialvars (zshrs-gen--words specialvars-file)))
    (with-temp-file out-file
      (insert ";;; zshrs-stdlib.el --- Generated zshrs builtin tables -*- lexical-binding: t; -*-\n\n")
      (insert ";; GENERATED by scripts/gen-stdlib.sh from `zshrs --dump-reflection'\n")
      (insert ";; (.builtins / .extensions / .special_vars).\n")
      (insert (format ";; zshrs %s — %s builtins, %s extensions, %s special vars.\n"
                      ver nbuiltins nextensions nspecialvars))
      (insert ";; Do not edit by hand; rerun the generator after a zshrs upgrade.\n\n")
      (insert ";;; Code:\n\n")
      (insert (zshrs-gen--regexp-form
               "zshrs-builtins-regexp" builtins
               "Symbol-bounded regexp matching every zshrs builtin name (generated)."))
      (insert (zshrs-gen--regexp-form
               "zshrs-extensions-regexp" extensions
               "Symbol-bounded regexp matching zshrs-specific extension builtins (generated)."))
      (insert (zshrs-gen--regexp-form
               "zshrs-special-vars-regexp" specialvars
               "Symbol-bounded regexp matching zshrs special variable names (generated)."))
      (insert "(provide 'zshrs-stdlib)\n")
      (insert ";;; zshrs-stdlib.el ends here\n"))))

(provide 'gen-stdlib)
;;; gen-stdlib.el ends here
